[package]
name = "gsp"
version = "0.1.3"
edition = "2021"

authors = ["Baptiste Roux"]

description = """
Simple CLI to switch between gcloud projects.
"""

keywords = ["gcloud", "gcp"]
categories = ["command-line-utilities", "config"]

homepage = "https://github.com/BapRx/gsp"
repository = "https://github.com/BapRx/gsp"
license = "MIT"
readme = "README.md"

[dependencies]
clap = { version = "4.4.5", features = ["derive"] }
clap_complete = "4.4.1"
log = "0.4.20"
prettytable = "0.10.0"
rust-ini = "0.19.0"
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
simplelog = { version = "0.12.1", features = ["paris"] }
skim = "0.10.4"
